import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Feather, Globe2, Hand, Menu } from "lucide-react";
import { products } from "@/lib/products";

const hero = "https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=2200&q=85";
export default function HomePage() {
  return <main>
    <header className="site-header"><Link className="wordmark" href="/">UQAAB<span>CARPET</span></Link><nav><Link href="/about">Our story</Link><Link href="/products">Carpets</Link><Link href="/craftsmanship">Craftsmanship</Link><Link href="/contact">Contact</Link></nav><Link className="header-cta" href="/contact">Enquire <ArrowUpRight size={15}/></Link><button className="mobile-menu" aria-label="Menu"><Menu/></button></header>
    <section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(24,14,24,.76),rgba(24,14,24,.12)),url(${hero})`}}><div className="hero-copy"><p className="eyebrow light">UQAAB NAWIN AFGHANISTAN LTD. · EST. 2015</p><h1>Woven by hand.<br/><em>Rooted in heritage.</em></h1><p className="hero-intro">Afghan carpets shaped by generations of artistry, made to bring warmth, character, and enduring craft into the spaces we live in.</p><div className="hero-actions"><Link className="button button-light" href="/products">Explore the collection <ArrowUpRight size={16}/></Link><Link className="text-link light" href="/about">Discover our story <ArrowDownRight size={16}/></Link></div></div><div className="hero-note"><span>01 / 03</span><span>Afghan craft, for the world</span></div></section>
    <section className="intro section-wrap"><div className="eyebrow">A LIVING TRADITION</div><div className="intro-grid"><h2>More than a carpet.<br/><em>A piece of our story.</em></h2><div><p>Founded in Kabul in 2015, Uqaab Nawin Afghanistan Ltd. brings the rich language of Afghan weaving to homes and spaces around the world. Each carpet begins with a tradition—and finds its own expression through the hands that make it.</p><Link className="underlined-link" href="/about">Get to know Uqaab <ArrowUpRight size={15}/></Link></div></div><div className="stats"><div><strong>2015</strong><span>Founded in Kabul</span></div><div><strong>10,000+ m²</strong><span>Manufactured to date*</span></div><div><strong>Global</strong><span>Markets served*</span></div></div><p className="fine-print">*Company figures supplied by Uqaab Nawin Afghanistan Ltd.; verify before publication.</p></section>
    <section className="collection-band"><div className="section-wrap collection-head"><div><p className="eyebrow light">THE COLLECTION</p><h2>Find the feeling<br/><em>you want to live with.</em></h2></div><Link className="button button-outline" href="/products">View all carpets <ArrowUpRight size={16}/></Link></div><div className="product-grid">{products.slice(0,3).map((p,i)=><Link className="product-card" href={`/products/${p.slug}`} key={p.slug}><div className={`product-art art-${i+1}`}><span>UQAAB / COLLECTION {String(i+1).padStart(2,"0")}</span><div className="rug-motif"><div/></div></div><div className="product-meta"><div><span>{p.collection}</span><h3>{p.name}</h3></div><ArrowUpRight size={18}/></div><p className="product-caption">Price on inquiry</p></Link>)}</div></section>
    <section className="craft-section section-wrap"><div className="craft-image" style={{backgroundImage:`url(${hero})`}}><span>THE ART OF MAKING</span></div><div className="craft-copy"><p className="eyebrow">MADE WITH INTENTION</p><h2>Every thread<br/>holds <em>a tradition.</em></h2><p>From considered materials to the rhythm of the loom, the craft is a conversation between heritage and the hands carrying it forward.</p><div className="craft-values"><div><Hand/><span>Human hands<br/>behind every weave</span></div><div><Feather/><span>Materials chosen<br/>with care</span></div><div><Globe2/><span>Afghan craft,<br/>shared globally</span></div></div><Link className="underlined-link" href="/craftsmanship">Explore our craftsmanship <ArrowUpRight size={15}/></Link></div></section>
    <section className="quote-section"><p className="eyebrow light">MADE IN AFGHANISTAN</p><blockquote>“A carpet is not simply made.<br/>It is <em>patiently brought to life.</em>”</blockquote><Link className="text-link light" href="/contact">Begin an enquiry <ArrowUpRight size={16}/></Link></section>
    <footer className="footer"><div className="footer-top"><Link className="wordmark footer-mark" href="/">UQAAB<span>CARPET</span></Link><p>Afghan craftsmanship.<br/>A tradition carried forward.</p><div className="footer-links"><Link href="/about">About</Link><Link href="/products">Products</Link><Link href="/services">Services</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Uqaab Nawin Afghanistan Ltd.</span><span>Kabul, Afghanistan</span><Link href="/admin">Admin</Link></div></footer>
  </main>;
}
