"use client";
import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type ProductRow={id?:string;slug:string;name:string;collection_type:string;size:string;quality:string;materials:string;washing_type:string;pile_type:string;description:string;price_label:string;front_image:string|null;back_image:string|null;detail_image:string|null;status:"draft"|"published"|"archived";sort_order:number};
const blank:ProductRow={slug:"",name:"",collection_type:"",size:"Confirm dimensions",quality:"Confirm with Uqaab team",materials:"Confirm composition",washing_type:"Confirm care instructions",pile_type:"Confirm construction",description:"",price_label:"Price on inquiry",front_image:null,back_image:null,detail_image:null,status:"draft",sort_order:0};
const fields:(keyof ProductRow)[]=["name","slug","collection_type","size","quality","materials","washing_type","pile_type","description","price_label"];
export default function AdminWorkspace(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [session,setSession]=useState<any>(null);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [rows,setRows]=useState<ProductRow[]>([]);const [draft,setDraft]=useState<ProductRow>(blank);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!supabase)return;const {data,error}=await supabase.from("products").select("*").order("sort_order").order("name");if(error)setStatus(error.message);else setRows((data||[]) as ProductRow[]);},[supabase]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);if(next)load();});return()=>subscription.unsubscribe();},[supabase,load]);
 async function signIn(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setStatus("");const {error}=await supabase.auth.signInWithPassword({email,password});setStatus(error?error.message:"Signed in.");setBusy(false);}
 async function save(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setStatus("");const payload={...draft};delete payload.id;const result=draft.id?await supabase.from("products").update(payload).eq("id",draft.id):await supabase.from("products").insert(payload);if(result.error)setStatus(result.error.message);else{setStatus("Product saved.");setDraft(blank);await load();}setBusy(false);}
 async function remove(){if(!supabase||!draft.id)return;setBusy(true);const {error}=await supabase.from("products").delete().eq("id",draft.id);setStatus(error?error.message:"Product deleted.");if(!error){setDraft(blank);await load();}setBusy(false);}
 async function upload(e:ChangeEvent<HTMLInputElement>,field:"front_image"|"back_image"|"detail_image"){if(!supabase||!draft.id||!e.target.files?.[0]){setStatus("Save the product first, then upload its images.");return;}const file=e.target.files[0];if(!["image/jpeg","image/png","image/webp","image/avif"].includes(file.type)){setStatus("Use a JPG, PNG, WebP, or AVIF image.");return;}if(file.size>15*1024*1024){setStatus("Image must be smaller than 15 MB.");return;}setBusy(true);const path=`products/${draft.id}/${field}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase.storage.from("site-media").upload(path,file,{upsert:false,contentType:file.type});if(error)setStatus(error.message);else{const {data}=supabase.storage.from("site-media").getPublicUrl(path);const next={...draft,[field]:data.publicUrl};const {error:updateError}=await supabase.from("products").update({[field]:data.publicUrl}).eq("id",draft.id);if(updateError)setStatus(updateError.message);else{setDraft(next);setStatus("Image uploaded.");await load();}}setBusy(false);e.target.value="";}
 if(!supabase)return <div className="admin-card"><h2>Supabase is not configured</h2><p>Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to your deployment environment, then restart the app.</p></div>;
 if(!session)return <form className="form admin-card" onSubmit={signIn}><h2>Administrator sign in</h2><p>Sign in with the Supabase Auth account that has an admin or editor role.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{status&&<p role="status" className="notice">{status}</p>}</form>;
 return <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(0,1.15fr)",gap:24,alignItems:"start"}}><div className="admin-card"><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><h2>Products</h2><button className="small-button" onClick={()=>setDraft({...blank})}>+ New</button></div><p className="fine-print">Select a product to edit. Published items may appear on the public site once the storefront is connected to Supabase.</p><div style={{display:"grid",gap:8}}>{rows.map(row=><button key={row.id} className="product-select" onClick={()=>setDraft(row)}><span><strong>{row.name}</strong><small>{row.slug}</small></span><span className="status-pill">{row.status}</span></button>)}</div>{rows.length===0&&<p>No products in Supabase yet. Create your first product.</p>}<button className="small-button" style={{marginTop:18}} onClick={async()=>{await supabase.auth.signOut();setStatus("Signed out.");}}>Sign out</button></div><form className="form admin-card" onSubmit={save}><h2>{draft.id?"Edit product":"Create product"}</h2>{fields.map(field=><label key={field}>{({name:"Product name",slug:"URL slug",collection_type:"Collection type",size:"Size",quality:"Quality",materials:"Materials",washing_type:"Washing type",pile_type:"Pile type",description:"Description",price_label:"Price label"} as Record<string,string>)[field]}{field==="description"?<textarea value={String(draft[field]??"")} onChange={e=>setDraft({...draft,[field]:e.target.value})} required/>:<input value={String(draft[field]??"")} onChange={e=>setDraft({...draft,[field]:e.target.value})} required={["name","slug"].includes(field)} />}</label>)}<label>Publication status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as ProductRow["status"]})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Sort order<input type="number" value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:Number(e.target.value)})}/></label><button disabled={busy}>{busy?"Saving…":"Save product"}</button>{draft.id&&<><h2>Product images</h2>{(["front_image","back_image","detail_image"] as const).map(field=><label key={field}>{field.replace("_"," ")}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>upload(e,field)}/>{draft[field]&&<a href={draft[field]||"#"} target="_blank" rel="noreferrer">View current image</a>}</label>)}<button type="button" className="danger-button" onClick={remove} disabled={busy}>Delete product</button></>}{status&&<p role="status" className="notice">{status}</p>}</form></div>;
}
