import Link from "next/link";
import { notFound } from "next/navigation";
const pages:Record<string,{eyebrow:string,title:string,subtitle:string,sections:{title:string,body:string}[]}>={
about:{eyebrow:"OUR STORY",title:"Afghan heritage, woven forward.",subtitle:"Uqaab Nawin Afghanistan Ltd. was founded in Kabul in 2015 with a commitment to handmade carpets, cultural craft, and sharing Afghan artistry with the world.",sections:[{title:"Our company",body:"According to company-provided information, Uqaab has manufactured more than 10,000 square meters of carpets and serves local and international markets, including the United States, China, Europe, and the United Arab Emirates."},{title:"Our vision",body:"To be a global leader in handcrafted Afghan carpets, preserving cultural heritage while inspiring appreciation for authentic artistry and sustainable weaving traditions."},{title:"Our mission",body:"To create premium handmade carpets, preserve traditional techniques, expand international reach, support responsible livelihoods, and deliver thoughtful customer experiences."}]},
craftsmanship:{eyebrow:"THE MAKING",title:"A tradition held in every thread.",subtitle:"Handmade carpet making is a practice of patience, skill, and knowledge passed between generations.",sections:[{title:"Materials and preparation",body:"Material selection and preparation shape the character of a carpet. Exact fibre content and sourcing vary by product and will be listed on each confirmed product page."},{title:"The work of weaving",body:"Pattern, colour, and construction come together through skilled hands. Uqaab’s product pages will identify the actual construction and pile type once confirmed."},{title:"Finishing and care",body:"Finishing and care depend on the carpet’s materials and construction. Always follow the care instructions supplied for the individual piece."}]},
services:{eyebrow:"WORK WITH UQAAB",title:"A considered approach to every order.",subtitle:"Connect with our team for product enquiries, wholesale discussions, export requests, and custom carpet projects.",sections:[{title:"Wholesale and trade",body:"Share your target quantities, preferred styles, dimensions, destination, and timeline to begin a trade enquiry."},{title:"Custom requests",body:"Tell us about your design direction, palette, size, and intended space. Custom options and lead times are confirmed case by case."},{title:"Export enquiries",body:"For international enquiries, include your destination country and required delivery timeline so our team can respond with relevant information."}]},
faq:{eyebrow:"HELP & INFORMATION",title:"Questions, answered with care.",subtitle:"A few useful starting points. Product-specific details are confirmed directly with our team.",sections:[{title:"How can I request a price?",body:"Use the enquiry form or contact us by WhatsApp or email. Include the product name, dimensions, quantity, and destination."},{title:"Can I request a custom size or design?",body:"Send your requirements to our team. Availability, feasibility, pricing, and lead time must be confirmed for each request."},{title:"What materials are used?",body:"Material composition varies by product. Please refer to the confirmed product specification or ask our team before ordering."},{title:"How should I wash my carpet?",body:"Care depends on fibre and construction. Use the product-specific care instructions and consult a qualified rug-care professional when needed."},{title:"Do you handle international enquiries?",body:"The company reports serving international markets. Contact us with your destination and order requirements to discuss current options."}]}}
export function generateStaticParams(){return Object.keys(pages).map(page=>({page}));}
export async function generateMetadata({params}:{params:Promise<{page:string}>}){const {page}=await params;return {title:pages[page]?.eyebrow??"Uqaab Carpet"};}
export default async function ContentPage({params}:{params:Promise<{page:string}>}){const {page}=await params;const data=pages[page];if(!data)notFound();return <><header className="site-header"><Link className="wordmark" href="/">UQAAB<span>CARPET</span></Link><nav><Link href="/about">Our story</Link><Link href="/products">Carpets</Link><Link href="/craftsmanship">Craftsmanship</Link><Link href="/contact">Contact</Link></nav><Link className="header-cta" href="/contact">Enquire</Link></header><section className="page-hero"><p className="eyebrow light">{data.eyebrow}</p><h1>{data.title}</h1><p>{data.subtitle}</p></section><section className="page-content">{data.sections.map((s,i)=><article key={s.title} style={{maxWidth:780,marginBottom:50}}><p className="eyebrow">0{i+1} / {data.sections.length}</p><h2>{s.title}</h2><p>{s.body}</p></article>)}<Link className="button" style={{background:"var(--plum)",color:"white"}} href="/contact">Talk to our team <ArrowUpRight size={15}/></Link></section><footer className="footer"><div className="footer-bottom"><span>© {new Date().getFullYear()} Uqaab Nawin Afghanistan Ltd.</span><Link href="/">Home</Link><Link href="/products">Products</Link></div></footer></>}
